{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.8.0.aar",
          "url": "work-runtime-ktx-2.8.0.aar",
          "size": 23390,
          "sha512": "a00ce719d665da99d138b19c0b5fa67e70287337d1db07744c791914f913750a4632181413f3d7fc9ffd504b5d7ddd981d64ab2edb257108a19b5c799d9053e4",
          "sha256": "e60f72decf692054edcbec5775c543ff7db629edaa0f893056615a300e838b21",
          "sha1": "3a68c3e47c0963300407ef62b2e08b970cecdb61",
          "md5": "26f6ff84a47f3d323d8aa4c6ab3b446f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.8.0.aar",
          "url": "work-runtime-ktx-2.8.0.aar",
          "size": 23390,
          "sha512": "a00ce719d665da99d138b19c0b5fa67e70287337d1db07744c791914f913750a4632181413f3d7fc9ffd504b5d7ddd981d64ab2edb257108a19b5c799d9053e4",
          "sha256": "e60f72decf692054edcbec5775c543ff7db629edaa0f893056615a300e838b21",
          "sha1": "3a68c3e47c0963300407ef62b2e08b970cecdb61",
          "md5": "26f6ff84a47f3d323d8aa4c6ab3b446f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.8.0-sources.jar",
          "url": "work-runtime-ktx-2.8.0-sources.jar",
          "size": 6106,
          "sha512": "d85853e056640a5a1bd7c988317b5ba6762937343bd829aab6038945198ef3ac8252a7504dc387debf7e7eb7cc0c69dd27f859a11a7a8d0688996f38ccb7ebea",
          "sha256": "9a6f1c652e7188dfa170c69864210c7cfdfe0e1d1051a2ceb16eeb111d5aece2",
          "sha1": "fd60c8ce0d488a5426864314d58b14de2abd7375",
          "md5": "3ed5ef5e1a536dd1644ffc417c0ab592"
        }
      ]
    }
  ]
}