{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.0.aar",
          "url": "navigation-fragment-ktx-2.4.0.aar",
          "size": 1778,
          "sha512": "3be5c05e01970905498f300dfea493a46aadc84813a3bb574bb30e930d46c1fe0696a66d61eb66f84d42ca3a3f3f6b6ccc1e9fa523c316c14e8aa44d38a88411",
          "sha256": "747166784725f73badf9686230a5c9e3f7cadeff15e244eb83a1f307975dd5c1",
          "sha1": "4bf4d6a234110e9d107a217f5c2fd708326c1c28",
          "md5": "7351449cea6b8ff5b2b5c8ad5b3f6af0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.0.aar",
          "url": "navigation-fragment-ktx-2.4.0.aar",
          "size": 1778,
          "sha512": "3be5c05e01970905498f300dfea493a46aadc84813a3bb574bb30e930d46c1fe0696a66d61eb66f84d42ca3a3f3f6b6ccc1e9fa523c316c14e8aa44d38a88411",
          "sha256": "747166784725f73badf9686230a5c9e3f7cadeff15e244eb83a1f307975dd5c1",
          "sha1": "4bf4d6a234110e9d107a217f5c2fd708326c1c28",
          "md5": "7351449cea6b8ff5b2b5c8ad5b3f6af0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-ktx-2.4.0-sources.jar",
          "url": "navigation-fragment-ktx-2.4.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
