{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.5.0.aar",
          "url": "room-runtime-2.5.0.aar",
          "size": 237004,
          "sha512": "6df98d2c188d942c2b0dbbbacf76d4d5ee1d64081552bfa6b83a0f08ed6bd4f20e699430f295796d445a2c6396d9e3edf791289cf6c83109901568e8cae50bf9",
          "sha256": "9882841877a4437f2002ed9d353f757a5452e13b4ab0ebf195c63ccf0e2e0847",
          "sha1": "42a70249423cc0d4245c0a072d4796eae2c4a867",
          "md5": "7e8b8e44c6d5ec2e5e6186fcd5491b1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.5.0.aar",
          "url": "room-runtime-2.5.0.aar",
          "size": 237004,
          "sha512": "6df98d2c188d942c2b0dbbbacf76d4d5ee1d64081552bfa6b83a0f08ed6bd4f20e699430f295796d445a2c6396d9e3edf791289cf6c83109901568e8cae50bf9",
          "sha256": "9882841877a4437f2002ed9d353f757a5452e13b4ab0ebf195c63ccf0e2e0847",
          "sha1": "42a70249423cc0d4245c0a072d4796eae2c4a867",
          "md5": "7e8b8e44c6d5ec2e5e6186fcd5491b1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.5.0-sources.jar",
          "url": "room-runtime-2.5.0-sources.jar",
          "size": 88585,
          "sha512": "3a19e8fe505a248709e5e7aea4701366e7e23191babea856632338cc50ebc92742ba262a06feb88329f8510f9acf4663ec7112cff3748b7faa2e37974bb6641f",
          "sha256": "972bd3b112dd84dedb58d7ee26ac62f8b821b36e7ba215ff98557bf48ac46f3d",
          "sha1": "8ba2410a7a67667a7cb11ca0a9be8db5237d8942",
          "md5": "deb9656bbcad99b1054acdd54320aa95"
        }
      ]
    }
  ]
}