{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.0.aar",
          "url": "work-runtime-2.8.0.aar",
          "size": 1665097,
          "sha512": "b7d3effbad36af1e080b4745e22466e8db2f752eab5ae45fe33386996c0884405fd8b07b6ea5b9e4b252816b4168370bde902ada24d0884146af7cbea5e204d8",
          "sha256": "e2d1012085b0c083e457aca9c5229f5722f5aa5421d9ae53f99e2645eb75b5ae",
          "sha1": "846d2e9653697a890e6cf7dcad40b801068406f0",
          "md5": "a12d3bffe26474103a2e01f8885a9633"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.0.aar",
          "url": "work-runtime-2.8.0.aar",
          "size": 1665097,
          "sha512": "b7d3effbad36af1e080b4745e22466e8db2f752eab5ae45fe33386996c0884405fd8b07b6ea5b9e4b252816b4168370bde902ada24d0884146af7cbea5e204d8",
          "sha256": "e2d1012085b0c083e457aca9c5229f5722f5aa5421d9ae53f99e2645eb75b5ae",
          "sha1": "846d2e9653697a890e6cf7dcad40b801068406f0",
          "md5": "a12d3bffe26474103a2e01f8885a9633"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-2.8.0-sources.jar",
          "url": "work-runtime-2.8.0-sources.jar",
          "size": 268380,
          "sha512": "f06fc11c82030a6217e89dd42f609fcc8ee69ed3599a338e615eeaa8ed2287fb9592cb402536ae045922e67de0ef2b6586f0905eee77e4c6200f5e9ab8990afb",
          "sha256": "8aa53b1c2d10bb65ba4b7ecd731ae6f2d400ad3ccfba3423538d41857761b1ec",
          "sha1": "9e0d06dd3546740e0d51158b195ab18f31c14322",
          "md5": "5d6953705c62c7299f1c5ced52412e2a"
        }
      ]
    }
  ]
}