{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-2.3.0.aar",
          "url": "sqlite-2.3.0.aar",
          "size": 30029,
          "sha512": "6a0bdf44f6bbc73c455f7cfaaa1560049dbc2048eaedaf88e7ad5f423c0a1a5b4b2c1ae771743b2f3af3603edb3f555190798aeac616d70deccb0862fc584a7f",
          "sha256": "d3d37e2403c523a5cee1983b27a6de7ad8dcbb502f446c3f76fca50ed73ce562",
          "sha1": "3dc5b3c69a6d20d8228fd60f3c6ef97f2f416efe",
          "md5": "629514d65d1322e06a9b3d1bcaba1c35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-2.3.0.aar",
          "url": "sqlite-2.3.0.aar",
          "size": 30029,
          "sha512": "6a0bdf44f6bbc73c455f7cfaaa1560049dbc2048eaedaf88e7ad5f423c0a1a5b4b2c1ae771743b2f3af3603edb3f555190798aeac616d70deccb0862fc584a7f",
          "sha256": "d3d37e2403c523a5cee1983b27a6de7ad8dcbb502f446c3f76fca50ed73ce562",
          "sha1": "3dc5b3c69a6d20d8228fd60f3c6ef97f2f416efe",
          "md5": "629514d65d1322e06a9b3d1bcaba1c35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-2.3.0-sources.jar",
          "url": "sqlite-2.3.0-sources.jar",
          "size": 20897,
          "sha512": "880881272c72e2cb60580cd15441e58b5b43451b6e7ad82e44575be83f3dd7a3223efd229da4ae6b000e5704f0e9dd290a4dc5af3433ae122a330f3debb39c54",
          "sha256": "d3ddccba5f0add13d981a358e76e192bc46607c1ba992b489a988f22fc9f5b29",
          "sha1": "324fc149adb970e71242ce7131fe387e7fa59ffb",
          "md5": "bc59dd3e902bc607eed6bd2a838f7af7"
        }
      ]
    }
  ]
}