{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0.aar",
          "url": "navigation-ui-2.4.0.aar",
          "size": 95056,
          "sha512": "1f1def46dfd882778b0d130b7d970741968cb67226e23afcc2e8c9ba62625557b1f05f7af3c3faf45888ab9058aafbf7988141fbfac68a4b0e2ba0c940f5c459",
          "sha256": "32fcf340ac6329d734560fdc3fb3d538e4d417b81390b74423d1a9ce0410d83f",
          "sha1": "78a4337da4364dbc8f72ba37895aef5f0f6153cc",
          "md5": "ef349e06113fb28d9f9b534e625fc33d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0.aar",
          "url": "navigation-ui-2.4.0.aar",
          "size": 95056,
          "sha512": "1f1def46dfd882778b0d130b7d970741968cb67226e23afcc2e8c9ba62625557b1f05f7af3c3faf45888ab9058aafbf7988141fbfac68a4b0e2ba0c940f5c459",
          "sha256": "32fcf340ac6329d734560fdc3fb3d538e4d417b81390b74423d1a9ce0410d83f",
          "sha1": "78a4337da4364dbc8f72ba37895aef5f0f6153cc",
          "md5": "ef349e06113fb28d9f9b534e625fc33d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.4.0-sources.jar",
          "url": "navigation-ui-2.4.0-sources.jar",
          "size": 20800,
          "sha512": "6a04f004d3ace555ba21dcfec22dc62dda488516ecf19e2d8e8d4a19f8e8ed43bfbd0857a2a97d4b3221bcf36c38e024ce56630de4debe75bdc531acf2808a0c",
          "sha256": "cf467e3bde7f9bb5b09e3405aa27b4cca09962b3940e65442b3d9075158f4752",
          "sha1": "89d1adbee4f51f0894d7bbd09355ea2dadd307c1",
          "md5": "6ea3eb2e7c238ce796a91a66fa3948bb"
        }
      ]
    }
  ]
}
