{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0.aar",
          "url": "navigation-ui-ktx-2.4.0.aar",
          "size": 1768,
          "sha512": "db40663bda827fd392f73dd5926f27e02b1663076464aef81e4c38a48c5b0b421d405217e7d6f40ad3c04c8b94ea9afb6b8ffcde6ff601764facaad4acf0127d",
          "sha256": "74c7d3dc0b1dc4e0d02243921b0da977bdba780edd097f5b30de42c7fac76eb8",
          "sha1": "1bd08e2e3017e85969b9844ddbe079c42293e18f",
          "md5": "98b592f7dd078b994f0d5b57cb06e022"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0.aar",
          "url": "navigation-ui-ktx-2.4.0.aar",
          "size": 1768,
          "sha512": "db40663bda827fd392f73dd5926f27e02b1663076464aef81e4c38a48c5b0b421d405217e7d6f40ad3c04c8b94ea9afb6b8ffcde6ff601764facaad4acf0127d",
          "sha256": "74c7d3dc0b1dc4e0d02243921b0da977bdba780edd097f5b30de42c7fac76eb8",
          "sha1": "1bd08e2e3017e85969b9844ddbe079c42293e18f",
          "md5": "98b592f7dd078b994f0d5b57cb06e022"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-sources.jar",
          "url": "navigation-ui-ktx-2.4.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
