{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.3.0.aar",
          "url": "sqlite-framework-2.3.0.aar",
          "size": 32063,
          "sha512": "803bd63eb0dca95fbad506838e1aec512f125c3d296c999c605870a64af9bd83a8a19861c74ee9bfa4bc2529109d49c059a274d4a97a27917ad6a55a0ac190af",
          "sha256": "8b5bd3acef01ea781a8545bdf710b1c06182417669a1a68cd0ae4a536cdae827",
          "sha1": "bed458415a6998c914ceb5a71e99ff5417b95514",
          "md5": "3a4a0652d3e31f80776467a5abda612c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.3.0.aar",
          "url": "sqlite-framework-2.3.0.aar",
          "size": 32063,
          "sha512": "803bd63eb0dca95fbad506838e1aec512f125c3d296c999c605870a64af9bd83a8a19861c74ee9bfa4bc2529109d49c059a274d4a97a27917ad6a55a0ac190af",
          "sha256": "8b5bd3acef01ea781a8545bdf710b1c06182417669a1a68cd0ae4a536cdae827",
          "sha1": "bed458415a6998c914ceb5a71e99ff5417b95514",
          "md5": "3a4a0652d3e31f80776467a5abda612c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-framework-2.3.0-sources.jar",
          "url": "sqlite-framework-2.3.0-sources.jar",
          "size": 11140,
          "sha512": "f7a686665a7657e5221bda60951aa8d62bcaa0e5cedeade1a8ffdd2823f29547d92f95eb903b3a03e73917b478cfc8ae48802af3a26bda915bdc5fd12b85f58a",
          "sha256": "3c7233ded107a02c1436a7a0a05a6ae4287019fbf6328158428d6fb323db7a01",
          "sha1": "47588405611666b93fd4a38dfd590d5ddae15902",
          "md5": "fc0a329f5ef964d9c632cb70d42c6edf"
        }
      ]
    }
  ]
}