package pl.autokat.enums

enum class ProcessStep {
    NONE,
    SUCCESS,
    UNHANDLED_EXCEPTION,
    USER_NEVER_LOGGED,
    USER_FAILED_LOGIN,
    ELAPSED_DATE_LICENCE,
    USER_FAILED_SERIAL,
    NETWORK_FAILED,
    COMPANY_ELAPSED_LICENCE,
    NONE_COURSES
}