{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.4.0.aar",
          "url": "navigation-fragment-2.4.0.aar",
          "size": 57533,
          "sha512": "5275a972db6087ca7bcfb4d308b4442ced21b234fdc4e4b5823b9f23a8c13abadaed2268cdc696143fa2688c5f9281092203e4d1327213db045dfc877e9cd818",
          "sha256": "e67e6f98679d8d9622a9ea6412797391017ac6d903b060f30e3801e0b2117a09",
          "sha1": "bb6fbb4ead3880e8b5750020fe91a7490b7c0d8a",
          "md5": "e805351942e27240ed85cb6e51915eb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.4.0.aar",
          "url": "navigation-fragment-2.4.0.aar",
          "size": 57533,
          "sha512": "5275a972db6087ca7bcfb4d308b4442ced21b234fdc4e4b5823b9f23a8c13abadaed2268cdc696143fa2688c5f9281092203e4d1327213db045dfc877e9cd818",
          "sha256": "e67e6f98679d8d9622a9ea6412797391017ac6d903b060f30e3801e0b2117a09",
          "sha1": "bb6fbb4ead3880e8b5750020fe91a7490b7c0d8a",
          "md5": "e805351942e27240ed85cb6e51915eb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.4.0-sources.jar",
          "url": "navigation-fragment-2.4.0-sources.jar",
          "size": 23709,
          "sha512": "c33afadc26917362d4424126e4558a101fc7e8e624580d858e8a573a94a8d49639ab9100beba810e61d951458789435138a75575852d71a73b3ed8354f9b656c",
          "sha256": "045b4a4fb495ac82fb6cd7abe753fbe53d1754d4abfb4be9352a4a8651592522",
          "sha1": "83eb9ba36f36f08cb87db7db2cf0cf37523aad1b",
          "md5": "3cec0f7679486739596bd04b968f43a7"
        }
      ]
    }
  ]
}
